# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='billable',
            field=models.BooleanField(default=True),
        ),
    ]
