# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_entry_billable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('client', 'name', 'start')]),
        ),
    ]
