# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20160306_2331'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate_type',
        ),
        migrations.AddField(
            model_name='entry',
            name='unit_type',
            field=models.IntegerField(choices=[(1, 'hourly'), (8, 'daily'), (1, 'fixed')], default=1),
        ),
        migrations.AddField(
            model_name='rate',
            name='unit_type',
            field=models.IntegerField(choices=[(1, 'hourly'), (8, 'daily'), (1, 'fixed')], default=1),
        ),
    ]
